// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type NetworkTrackerNetKeyT struct {
	Comm      [16]int8
	Ifindex   uint32
	Proto     uint8
	Direction uint8
	Pad       [2]uint8
}

// LoadNetworkTracker returns the embedded CollectionSpec for NetworkTracker.
func LoadNetworkTracker() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NetworkTrackerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load NetworkTracker: %w", err)
	}

	return spec, err
}

// LoadNetworkTrackerObjects loads NetworkTracker and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*NetworkTrackerObjects
//	*NetworkTrackerPrograms
//	*NetworkTrackerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadNetworkTrackerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadNetworkTracker()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// NetworkTrackerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetworkTrackerSpecs struct {
	NetworkTrackerProgramSpecs
	NetworkTrackerMapSpecs
}

// NetworkTrackerSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetworkTrackerProgramSpecs struct {
	KprobeTcpCleanupRbuf *ebpf.ProgramSpec `ebpf:"kprobe_tcp_cleanup_rbuf"`
	KprobeTcpSendmsg     *ebpf.ProgramSpec `ebpf:"kprobe_tcp_sendmsg"`
	KprobeUdpRecvmsg     *ebpf.ProgramSpec `ebpf:"kprobe_udp_recvmsg"`
	KprobeUdpSendmsg     *ebpf.ProgramSpec `ebpf:"kprobe_udp_sendmsg"`
	KprobeUdpv6Sendmsg   *ebpf.ProgramSpec `ebpf:"kprobe_udpv6_sendmsg"`
	KretprobeUdpRecvmsg  *ebpf.ProgramSpec `ebpf:"kretprobe_udp_recvmsg"`
}

// NetworkTrackerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetworkTrackerMapSpecs struct {
	NetStats       *ebpf.MapSpec `ebpf:"net_stats"`
	UdpRecvIfindex *ebpf.MapSpec `ebpf:"udp_recv_ifindex"`
}

// NetworkTrackerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadNetworkTrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetworkTrackerObjects struct {
	NetworkTrackerPrograms
	NetworkTrackerMaps
}

func (o *NetworkTrackerObjects) Close() error {
	return _NetworkTrackerClose(
		&o.NetworkTrackerPrograms,
		&o.NetworkTrackerMaps,
	)
}

// NetworkTrackerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadNetworkTrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetworkTrackerMaps struct {
	NetStats       *ebpf.Map `ebpf:"net_stats"`
	UdpRecvIfindex *ebpf.Map `ebpf:"udp_recv_ifindex"`
}

func (m *NetworkTrackerMaps) Close() error {
	return _NetworkTrackerClose(
		m.NetStats,
		m.UdpRecvIfindex,
	)
}

// NetworkTrackerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadNetworkTrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetworkTrackerPrograms struct {
	KprobeTcpCleanupRbuf *ebpf.Program `ebpf:"kprobe_tcp_cleanup_rbuf"`
	KprobeTcpSendmsg     *ebpf.Program `ebpf:"kprobe_tcp_sendmsg"`
	KprobeUdpRecvmsg     *ebpf.Program `ebpf:"kprobe_udp_recvmsg"`
	KprobeUdpSendmsg     *ebpf.Program `ebpf:"kprobe_udp_sendmsg"`
	KprobeUdpv6Sendmsg   *ebpf.Program `ebpf:"kprobe_udpv6_sendmsg"`
	KretprobeUdpRecvmsg  *ebpf.Program `ebpf:"kretprobe_udp_recvmsg"`
}

func (p *NetworkTrackerPrograms) Close() error {
	return _NetworkTrackerClose(
		p.KprobeTcpCleanupRbuf,
		p.KprobeTcpSendmsg,
		p.KprobeUdpRecvmsg,
		p.KprobeUdpSendmsg,
		p.KprobeUdpv6Sendmsg,
		p.KretprobeUdpRecvmsg,
	)
}

func _NetworkTrackerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed networktracker_x86_bpfel.o
var _NetworkTrackerBytes []byte
