all:
  children:
    ebpf_monitored:
      hosts:
        myserver:
          ansible_host: 192.168.1.10
          ansible_user: myuser
        # myserver2:
        #   ansible_host: 192.168.1.11
        #   ansible_port: 2222
        #   ansible_user: myuser
